/* DO NOT EDIT THIS FILE - it is machine generated */
#include "test_JavaPing.h"
#include "../../c/ping.h"

JNIEXPORT jint JNICALL Java_test_JavaPing_ping4(JNIEnv *env, jclass jclazz, jstring hostname, jint timeout_sec) {
    const char* host = (*env)->GetStringUTFChars(env, hostname, NULL);
    int res = ping4(host, (int)timeout_sec);
    (*env)->ReleaseStringUTFChars(env, hostname, host);
    return (jint)res;
}

//void test() {
//    printf("Hello, test!\n");
//}
