/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JavaPing */

#ifndef _Included_test_JavaPing
#define _Included_test_JavaPing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JavaPing
 * Method:    ping4
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_test_JavaPing_ping4
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
